### ISSUE TITLE
CLI thinks `s` is a special character

### ISSUE THREAD

**Issue by esoubihe** [pankod/pankod-cli#21]
CLI thinks I'm trying to use a special character when the `s` letter is present.

https://clip.maxihost.com.br/d85e3993d5ca

**Comment by furkanacaryes** [comment]
Hi @ebsalberto!

Input gets validated by a simple [RegExp](https://github.com/pankod/pankod-cli/blob/74bd01819eda84f013fd8138ed084613ca5386be/src/modules/element-factory/workbenches/operations/validate.operation.ts#L18).  It only accepts __alphanumericals__. I can NOT reproduce the problem since `s` is a valid character. I think that's a lower level problem like keyboard language or any input setting.

Can you please try with alternating system and keyboard languages? And it would be so nice if you could provide some info about device, system version etc.

I'll be waiting for your next feedback!

**Comment by esoubihe** [comment]
Thanks, @futuredayv. 

I'm running Mac version 10.15.3 and my input source is U.S., so nothing special there. I've even opened the virtual keyboard and pressed s but the CLI didn't pick it up.

I've uninstalled the package from the project with `npm uninstall @pankod/pankod-cli` and installed it again without success. I'm running version 1.0.0 btw.

**Comment by furkanacaryes** [comment]
Hi again @ebsalberto!

Would you like to use a [manual build](https://gist.github.com/futuredayv/96bdc4f835fb42b109f10cf5872f4c31) of cli?

Actually, I would be glad if you try to. Run this brief shell script in any directory, preferably under /home.

To use it like it was installed as a global package, link it to the project  you are working on by:
```sh
cd yourAwesomeProject

npm link @pankod/pankod-cli
```

I will release a new minor version with some improvements and better UX in 2 months.

**Comment by furkanacaryes** [comment]
Hey @ebsalberto!

We just published a patched version! Can you please try to run with `Node 10.x` ?
